name: "Deploy Firebase Component"
description: "inputsで指定されたFirebaseのコンポーネントをデプロイします。PRに指定されたディレクトリの変更点がない場合は実行されません。"
inputs:
  target_component:
    description: "デプロイ対象のコンポーネント(main or link or functions)"
    required: true
  force_deploy_functions:
    type: boolean
    required: false
    default: false
  force_deploy_main:
    type: boolean
    required: false
    default: false
  force_deploy_link:
    type: boolean
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: "Git Checkout"
      uses: actions/checkout@v4

    - name: "Paths Filter"
      uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          main:
            - 'main.txt'
          link:
            - 'link.txt'
          functions:
            - 'functions.txt'

    # - name: "install packages"
    #   uses: asdf-vm/actions/install@v3

    - name: "Deploy"
      shell: bash
      run: |
        # node -v
        # firebase --version
        # gcloud --version
        ## 対象のcomponentに変更があったか確認
        TARGET_COMPONENT="${{inputs.target_component}}"
        FILTER=$(echo '${{ toJSON(steps.filter.outputs) }}' | jq -r .${TARGET_COMPONENT})
        FORCE_RUN=$(echo '${{ toJSON(inputs) }}' | jq -r ."force_run_${TARGET_COMPONENT}")
        echo '${{ toJSON(steps.filter.outputs) }}' | jq .
        echo '${{ toJSON(inputs) }}' | jq .

        if [[ "${FILTER}" == "true" || "${FORCE_RUN}" == "true" ]]; then
          ## main or linkがデプロイ対象だったら頭にhostingをつける
          DEPLOY_COMPONENT="${TARGET_COMPONENT}"
          if [[ "${TARGET_COMPONENT}" == "main" || "${TARGET_COMPONENT}" == "link" ]]; then
            DEPLOY_COMPONENT="hosting:${TARGET_COMPONENT}"
          fi

          echo "${{ inputs.target_component }} に変更があったためデプロイします。"
          echo "firebase deploy --only $DEPLOY_COMPONENT"
        else
          echo "No changes in ${{ inputs.target_component }}. Skip deploy."
        fi
        
