---
name: "Composite Action ${{input.message}}"
description: "[Test] Composite Action"
inputs:
  message:
    default: 'hello'
    required: false

runs:
  using: "composite"
  steps:
    - name: "Checkout"
      uses: actions/checkout@v2

    - name: "Hello World"
      shell: bash
      run: echo 'Hello World ${{input.message}}'
