name: "Main Step"
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, closed]

jobs:
  composite_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          message: 'from main'
