name: "Main Step"
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, closed]
  workflow_dispatch:
    inputs:
      force_deploy_functions:
        type: boolean
        required: true
        default: false
      force_deploy_main:
        type: boolean
        required: true
        default: false
      force_deploy_link:
        type: boolean
        required: true
        default: false

jobs:
  main_deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch' }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          target_component: 'main'
          force_deploy_main: '${{force_deploy_main}}'
  link_deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          target_component: 'link'
          force_deploy_link: '${{force_deploy_link}}'
  functions_deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          target_component: 'functions'
          force_deploy_functions: '${{force_deploy_functions}}'
