name: "Main Step"
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, closed]
  workflow_dispatch:

jobs:
  main_deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          target_component: 'main'
  link_deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          target_component: 'link'
  functions_deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          target_component: 'functions'
