name: "Main Step"
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, closed]

jobs:
  main_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          target_components: 'main'
  link_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          target_components: 'link'
  functions_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          target_components: 'functions'
